### PR TITLE
Fix for joi package upgrade

### PR DESCRIPTION
**Pull request by mattdavis90**
I've update the Joi call to satisfy the assert in the updated library

### CODE REVIEW

**Comment by piuccio** [comment]
I'm not a maintainer, but looking at the other PRs I think you should base your PR on `develop` instead of `master`

**Comment by mattdavis90** [comment]
I've rebased onto develop. Hopefully a maintainer get look over this soon as it looks like it is causing others issues now as well.

**Comment by mattdavis90** [comment]
Not sure why the tests failed they don't on my local machine with node v8 or v10

**Comment by jonathansamines** [comment]
@mattdavis90 I already re-ran the build and worked just fine. The problem is just with Joi@13?

**Comment by mattdavis90** [comment]
@jonathansamines I've rebased onto master. Yes looks like they did an update in 13.5 to how they assert the arguments. They were checking for an object previously but now they've added more logic.

https://github.com/hapijs/joi/issues/1552
https://github.com/hapijs/joi/blob/88b2a4272262725abce578a19cc47cbdfd7d3810/lib/types/string/index.js#L285

**Comment by Marsup** [comment]
Well, you were passing an argument that was entirely ignored, I think that's for the better ;)

**Comment by Marsup** [comment]
By the way, I think some people are waiting for a release, if you don't mind...

**Comment by jonathansamines** [comment]
Fixed at 2.2.1. Thanks for the heads-up @Marsup

**Pull request merged**
