### PR TITLE
use defaults to allow setting response_type

### PR DESCRIPTION
**Pull request by Lorenzovds**
In order to be compatible with multiple openID `response_type` values we need to be able to set this value manually, the current implementation assumes the `response_type` will always be `code` and overwrites arguments passed to the constructor.

see http://openid.net/specs/openid-connect-core-1_0.html#code-id_tokenExample

### CODE REVIEW

**Comment by jonathansamines** [comment]
Hi @Lorenzovds the functionality are you looking for is still achievable by using Object.assign, it is just a matter to change the arguments order when params are provided to it. Besides that, documentation needs to be updated, as well as the corresponding test-cases to get this merged.

Thanks!

**Comment by Lorenzovds** [comment]
Hello @jonathansamines, I'll update the PR with Object.assign and will update the docs and tests.
Thanks for the feedback.

Cheers

**Comment by Lorenzovds** [comment]
Hello @jonathansamines, could you have another look at this?

Cheers

**Comment by jbw** [comment]
Thanks, @Lorenzovds I had the same problem and made the change locally. Looking forward to having this merged in.

**Comment by jonathansamines** [comment]
Sorry for the late response. Merging this now, hopefully will release this night.

Thanks for your contribution :)

**Pull request merged**
