### PR TITLE
Allow mobile app authorization URI

### PR DESCRIPTION
**Pull request by hakantunc**
Add mobileAuthorizationUri to the configuration. authorizeURL uses this
path instead of authorizationPath when its second argument is true.

### CODE REVIEW

**Comment by andreareginato** [comment]
Hi @hakantunc. Thanks a lot for your pull request. I need some tests before accepting the changes.
All the best.

**Comment by jonathansamines** [comment]
Hi @hakantunc, this PR looks good, but there still some conflicts pending to be resolved. Also i´m not sure what´s the use case for this feature. I´m not completely sure about this it´s the best approach this problem.

I think we could ignore **site** property if not present and use the authorizationPath as the full mobile app URI, what do you think @andreareginato?

**Comment by andreareginato** [comment]
@jonathansamines I think we should discuss little more about it. Your final thought looks good to me.

**Comment by hakantunc** [comment]
I needed both site and mobile authorization URIs to use one of them depending on the user's device. I'm not sure if your suggestion would support this case.

**Comment by jonathansamines** [comment]
Temporary closed by #75, since there is no a proven use-case for supporting separated parameters. Feel free to re-open this if you found the solution provided is not covering your use case.

**Pull request closed without merging**
