### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ioMatrix**

### CODE REVIEW

**Comment by jonathansamines** [comment]
@ioMatrix Thanks for the contribution. However, I wonder if the same comprehension can be achieved by reading the [API documentation](https://github.com/lelylan/simple-oauth2/blob/master/API.md)? Would that helped in your case?

Originally, this documentation was all on the README file, but moved it as I wanted to further document all options and found the resulting documentation pretty dense for a README file. What do you think?

**Comment by ioMatrix** [comment]
Absolutely, that is a great document!! However, I did not run into that file while parsing the readme. I wish I had... would of saved a lot of time. Perhaps it could be linked under the first usage example to be a bit more visible for the TL:DR crowd :)?

**Comment by jonathansamines** [comment]
@ioMatrix Thanks for the reply, it is actually [linked](https://github.com/lelylan/simple-oauth2#api) in the README file, but almost at the end of the document. Would you mind moving it just below the first usage section?

**Comment by ioMatrix** [comment]
Ready

**Comment by jonathansamines** [comment]
@ioMatrix Thanks for the contribution

**Pull request merged**
