### PR TITLE
preserve old refresh token if new token does not contain refresh token

### LINKED ISSUE #431: Cannot refresh a second time after the first refresh
#### Context

* *node version*: v19.7.0
* *module version with issue*: 5.0.0
* *last module version without issue*: unknown
* *environment* (e.g. node, browser, native): node
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

* I am using authorization code flow to successfully fetch the first access token 1
* I can refresh token 1 to get token 2
* Token 2 cannot be refreshed because it no longer has a `refresh_token` associated. This is because our OAuth2 `/token` endpoint will only provide a new refresh token if the original refresh token is still within 60% of is validity period. It doesn't echo back the original refresh token.

This behavior is acceptable per [RFC 6749 Section 4.1.4](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.4)

#### What was the result you got?

Got a token that cannot be refreshed while the initial refresh token is still valid.

#### What result did you expect?

Tokens should be refreshable until the current refresh token is no longer valid.

Perhaps the library could consider using the current refresh token if the response does not include one ?

### PR DESCRIPTION
**Pull request by Uzlopak**
Fixes #431

### CODE REVIEW

**Comment by huzaifahj** [comment]
@jonathansamines Can this be merged?

**Comment by mindesik** [comment]
+

**Comment by jonathansamines** [comment]
Thanks for the contribution @Uzlopak

**Comment by jonathansamines** [comment]
Changes released in `v5.1.0`

**Comment by ptesny** [comment]
The fix is is not working. The refresh_token is being overwritten by `undefined`. Not sure how you tested it?


I get the 'refresh_token' set to `undefined` in lieu of the refresh token.

https://github.com/lelylan/simple-oauth2/blob/master/lib/access-token.js#L42-L52

The culprit is line https://github.com/lelylan/simple-oauth2/blob/master/lib/access-token.js#L52
it should be:

`response.refresh_token = this.token.refresh_token;`

in lieu of:

`response.refresh_token = this.refresh_token`

So the corrected code would like this:
```
if (response[REFRESH_TOKEN_PROPERTY_NAME] === undefined) {
      response.refresh_token = this.token.refresh_token;
    }
```
Due to this bug the latest version of the library broke my code:

```
const merged_accessToken = { ...token.token, ...refreshedToken.token };
```
as the `token.token.refresh_token` was being replaced by `undefined` from `refreshedToken.token.refresh_token`

**Comment by Uzlopak** [comment]
@ptesny oh! You are right. I am just testing if the key exists but not if the key is not undefined

Can you provide a PR?

**Pull request merged**
