### PR TITLE
Fixes #151: Update debug version to fix ReDoS attack vector

### LINKED ISSUE #151: Consider upgrading your debug version to fix ReDoS attack vector
It is all explained in your dependencies checker: https://nodesecurity.io/advisories/debug_regular-expression-denial-of-service

`debug` version should be upgraded to `^3.1.0` instead of `^3.0.1`.

### PR DESCRIPTION
**Pull request by Nargonath**
Just followed the guidelines of your dependencies checker. https://david-dm.org/lelylan/simple-oauth2 and https://nodesecurity.io/advisories/debug_regular-expression-denial-of-service.

I ran the tests suite and they all passed.

### CODE REVIEW

**Comment by jonathansamines** [comment]
As the dependencies are declared using caret (minor changes are included), this update will not fix the underlying issue which has not been resolved yet on the **debug** module. Will accept the PR though to update the dependency on the package.json file.

Thanks.

**Comment by Nargonath** [comment]
Thanks for merging the PR although I'm not sure I understand what you meant. According to `debug`'s release notes, the ReDoS attack vector has been fixed as of `v3.1.0` so upgrading the version in this package should do the trick, doesn't it?

**Comment by jonathansamines** [comment]
Yes, if that was the case then updating to 3.1.0 will fix the problem. However as the dependency was declared using caret, then that change would be taken automatically even without this PR. Note that all changes coming from 3.x.x would also be taken into account when downloading the dependency.

See https://semver.org/ for additional details.

**Comment by Nargonath** [comment]
Oh yeah sure, I misunderstood you. You are definitely right. I feel it is just better to update the version in the `package.json` as it implies we need this specific version at least. And it will quiet your dependencies checker as well. 👍

**Pull request merged**
