### PR TITLE
Add support for a different path for refresh tokens

### PR DESCRIPTION
**Pull request by theleewise**

### CODE REVIEW

**Comment by jonathansamines** [comment]
Hey @theleewise, these changes look good. Please add some integration tests to verify the new configuration option works as expected.

**Comment by theleewise** [comment]
😬  Oh man I'm not even sure where to even start with that. I have a basic understanding of writing tests but I'm at a bit of a loss on what to do here.

@jonathansamines Can you help or even point me in the right direction?

**Comment by jonathansamines** [comment]
Hey @theleewise you can look at this test in particular, I think it might be a good example to follow as it test exactly what you are doing here, except by overriding "tokenPath" (which is the only way right now of overriding the refresh tokens path)

https://github.com/lelylan/simple-oauth2/blob/52a710f215caaf5d763c8728a3f354ba4cc010d2/test/access-token.js#L330

Please let me know of any question you may have.

**Review by jonathansamines — APPROVED** [review]
Changes look good. Thanks for your contribution.

**Comment by jonathansamines** [comment]
Hi @theleewise. I released these changes as simple-oauth2@4.3.0

**Pull request merged**
