### PR TITLE
do not overwrite token.expires_at if it exists

### LINKED ISSUE #59: Token helper doesn’t play well with session
Just receiving the access token is not enough by itself, in real-world scenario, you have to save the access token to session. Now, on second page load, if I try to do:
``` javascript
oauth2.accessToken.create(req.session.token);
```
The token never expires because you always add seconds to current time: `(new Date).addSeconds(token.expires_in)` So I had to do something like this:

```javascript
function create(token) {
  // Re-add refresh_token if not present
  if (this.token && 'refresh_token' in this.token) {
    token.refresh_token = this.token.refresh_token;
  }

  // Restore timestamp if already created before
  this.token = token;
  this.token.expires_at = this.token.expires_at ?
      (new Date(this.token.expires_at)) : (new Date).addSeconds(token.expires_in);
  return this;
}
```
And save the resulting object to session instead of the original token. Because session can’t hold javascript functions and classes, On each page load, token helper is recreated from that object.

I might be far off here, but am I missing something?

### PR DESCRIPTION
**Pull request by bontibon**
fixes #59

### CODE REVIEW

**Comment by jonathansamines** [comment]
Hey @bontibon can you add test cases for this functionality?

**Comment by sankethkatta** [comment]
Any update on getting this merged in? I currently have to work around by manually setting `expires_at` and comparing the expiration myself.

**Comment by jonathansamines** [comment]
Hi @sankethkatta there is still a pending release where `date-utils` is replaced by `date-fns`. Also there is a pending request to avoid the singleton pattern on tokens saving. Util both are merged, I can´t merge this. Also there is a couple of problems with this PR, there is not test to cover this functionality change, and the PR was made to master and I need to be made against develop.

**Comment by shri2201** [comment]
I am trying to use this module but get TypeError: TypeError: Cannot assign to read only property 'expires_at' of access_token. 
`  function AccessToken(token) {
    this.token = token;
    this.token.expires_at = addSeconds((new Date), token.expires_in);

    return this;
  }`

**Pull request closed without merging**
