### PR TITLE
feat(typescript): Add typescript support

### PR DESCRIPTION
**Pull request by karlos1337**
Solve #109 
I've added all types based on lib docs and added also types tests using docs snippets and a package.json script to execute typescript tests, anyway please review it just in case I missed something, typescript syntax is easy to understand.

### CODE REVIEW

**Comment by karlos1337** [comment]
@jonathansamines, make sense for you?

**Comment by jonathansamines** [comment]
@karlos1337 Yes, I don't currently have to time to review this, but will take a deep look in a couple of weeks.

**Comment by karlos1337** [comment]
perfect, thx :)

**Comment by ThisIsMissEm** [comment]
@karlos1337 what's wrong with @types/simple-oauth2 ?

**Comment by karlos1337** [comment]
Sorry @ThisIsMissEm , didn't know that even exists, but, if can be done in the proper simple-oauth2 repo (PRs welcome said in the TS issue) why do it in other one separated from the main logic?

Not sure if my approach is the best one, only know tests pass, could be great import also @types/wreck (now I've just checked that also exists) instead of doing it from scratch for http options and could also add any @types/simple-oauth2 repo improvement too, but IMHO better in the main repo and avoid more dependencies or misunderstandings like this one, what do you think?

**Comment by jonathansamines** [comment]
@karlos1337 @ThisIsMissEm Finally decided on not adopting typescript. I am currently the only maintainer of this library and I am completely unfamiliar with how typescript works, therefore making this change a burden of maintenance. Since there are already typing definitions, and no further requests for this I'll assume those third party typings are working just fine.

**Pull request closed without merging**
