### PR TITLE
Support encoding body data in `json`

### PR DESCRIPTION
**Pull request by LegNeato**
The Amazon Developer Upload API requires params and auth info to be specified
in the body in JSON:

https://developer.amazon.com/public/apis/manage/developer-publishing/obtaining-an-access-token-for-the-developer-publishing-api#requesting-a-login-with-amazon-access-token

Before this change it was impossible to use this library to auth with that api. After, it works.

I did not change the current default behavior.

### CODE REVIEW

**Comment by LegNeato** [comment]
Friendly poke 👉 @jonathansamines

**Comment by LegNeato** [comment]
Another friendly poke 👉 @jonathansamines

**Comment by jonathansamines** [comment]
@LegNeato thanks for this additional, It just looks fine for me. I changed the target branch to `develop` and will release soon a new version.

**Comment by LegNeato** [comment]
Thanks for the merge!

**Pull request merged**
