### PR TITLE
Adds state generation and validation for Auth Code Grant

### PR DESCRIPTION
**Pull request by ashleywxwx**
I'm implementing a few different authentication libraries for different languages. I've loved the simplicity of this library so far, but I'd like to include state generation and validation as a part of this library in order to defend against CSRF attacks: https://tools.ietf.org/html/rfc6749#section-10.12

As to not introduce breaking changes, I've added an optional `generateState` config option, that allows the library to generate this state value, as well as two optional parameters `redirect_response_url` and `authorize_url` that allows the library to validate that the state has not been modified. This keeps the library stateless, while still providing this generation and validation functionality.

The only other thing I could think of would be to throw an error if `generateState` is provided, but `redirect_response_url` and `authorize_url` are not provided, but curious to your thoughts. Let me know if there is a better way to configure besides the `config.options.generateState`, if there are clearer naming conventions, documentation I can add, or additional test cases to cover.

I realized after the fact that I was working against node 12. If you plan on accepting #292 before this, then this should be good to go. But, if you would like to accept this first, I've got some code ready on a branch https://github.com/AndrewBell/simple-oauth2/tree/fork-develop-node-8 But, I'm having trouble running the tests, as ajv is failing with an unreported error.

### CODE REVIEW

**Comment by jonathansamines** [comment]
@AndrewBell In general I am not opposed to the idea of adding utilities to generate and validate state to the library. I have a couple of questions:

- Is there a reason to add the validation to the token generation function vs creating an additional validation function?
- Why do we receive URLs instead of the state value itself?

I am thinking that it might work better to create separate utilities, to perform both operations (generate and validate), but wanted to first clarify the reasoning behind the current implementation.

Perhaps the following API would work:

```js
const oauth2Module = require('simple-oauth2');
const { authorizationCode, generateState, validateState } =  oauth2Module.create(/* usual options*/);

const state = generateState(); // most of consumers would persist this value (e.g in cookies)
const redirectURL = authorizationCode.authorizeURL({ state });

// at a later point, once we receive the state value from the authorization server
validateState(state, stateFromAuthorizationServer); // throws if state is not valid

// or maybe we don't even need a validation function
if (state !== stateFromAuthorizationServer) // do something
```

Thoughts?

**Comment by jonathansamines** [comment]
@AndrewBell btw, it is ok to keep this development against develop branch (only supporting Node 12), but note that changes in develop will land in the next major version which I hope to release sometime in the next couple of months (maybe sooner).

**Comment by AndrewBell** [comment]
@jonathansamines 

Thanks for taking a look.

For the updated methods vs utility functions, my thought was to embed these in the existing functions to make it simpler for users to use, and it matched the other libraries I'm using (https://github.com/dmfs/oauth2-essentials and https://github.com/joestump/python-oauth2 FWIW). Ultimately I ended up writing these as utility functions in our current implementation anyway, and would be happy to update this PR to do the same if you prefer. 

As far as the URLs vs only state, I wanted to abstract away users having to parse out the query parameters. At least in my implementation, I was returning back the full URL returned from the auth server after the first redirect, so I was already handling the full `redirect_response_url` server-side anyway. But, I'm curious to how others have implemented state validation (e.g. Are they parsing the query parameter client side and only sending the state back to the server?). So, this was mostly an assumption on my part, but if we think users might not have the full URL, I could see a reason to expect only the state code, and not the full URLs. Otherwise, I think it'd be handy to handle parsing the query params for them.

Let me know your thoughts on both and I'll update the PR accordingly. Thanks!

**Comment by jonathansamines** [comment]
Hi @AndrewBell I still feel like supporting a utility-first approach would work better for a majority of use cases, as authorization code is meant to be used in a server implementation (usually on the authorization callback handler/controller), where the code is already available as a query param. Popular frameworks use this mechanism: [@hapi/bell](https://github.com/hapijs/bell/blob/master/lib/oauth.js#L251), [passport-oauth2](https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L164)

As an additional note, I recently re-designed the public API for this module. My new API suggestion based on those changes, would be:

```js
const { AuthorizationCode, State } = require('simple-oauth2');

const client = new AuthorizationCode(/* usual options */);
const state = State.generate(); // most of consumers would persist this value (e.g in cookies)

// redirect
const redirectURL = authorizationCode.authorizeURL({ state });

// at a later point, once we receive the state value back from the authorization server
State.validate(stateFromAuthorizationServer); // throws if state is not valid
```

Let me know your thoughts about it.

**Comment by AndrewBell** [comment]
@jonathansamines That sounds good. I'll update this when I get a chance, thanks for the guidance!

**Comment by jonathansamines** [comment]
Hey @ashleywxwx , I will close this PR as it has been several years since the last update. Feel free to reopen if you are still interested in incorporating these changes

**Pull request closed without merging**
