### PR TITLE
Adding the possibility to define body and json options

### PR DESCRIPTION
**Pull request by fgd99**
In order to be able to pass a json body in an API call

### CODE REVIEW

**Comment by jonathansamines** [comment]
Hi @fgd99 do you have an use-case for this feature? I just want to avoid bloating the public api with a lot of edge cases and weird property behaviours.

**Comment by fgd99** [comment]
Hi,

This resource for instance
http://support.gnip.com/apis/powertrack/api_reference.html#AddRules that
specifies a JSON request body.

Another exemple with the Github API
https://developer.github.com/v3/#http-verbs

For POST, PATCH, PUT, and DELETE requests, parameters not included in the
URL should be encoded as JSON with a Content-Type of 'application/json':

curl -i -u username -d '{"scopes":["public_repo"]}'
https://api.github.com/authorizations


Le lun. 4 avr. 2016 à 00:11, Jonathan Samines <notifications@github.com> a
écrit :

**Comment by sgulseth** [comment]
Another example of an implementation that requires body to be set: http://docs.quay.io/api/swagger/#!/tag/changeTagImage

**Comment by gertjana** [comment]
Any objections still about merging this? 
we have a rest-full api with oAuth2 where creating resources means posting JSON in the body of the request. So i would love to see this merged.

**Comment by jonathansamines** [comment]
Hi @fgd99 @gertjana although that is definitely true, most of apis dealing with resource creation and modification requires send the body as a post request. This library purpose is only deal with the oauth resources. Which I think we are covering the standard way to deal with them. Please let me know if I am still missing something.

**Comment by gertjana** [comment]
Actually we are going to allow people to register their own client id/secret which will create (what I assume you mean by) 'oauth resources' 
for now I forked the pull request to unblock me from using this library

**Comment by jonathansamines** [comment]
@gertjana Good to know, though that is a functionality of an oauth-server. This library is only meant to be used to get OAuth tokens by using one of the know oauth grant_types.

**Pull request closed without merging**
