### PR TITLE
Option rejectUnauthorized could not be set to false.

### PR DESCRIPTION
**Pull request by netgusto**
Option rejectUnauthorized could not be set to false due to improper presence test.

### CODE REVIEW

**Comment by jonathansamines** [comment]
Hi @netgusto not sure how the current validation is affecting you, since a `non-existing` property would be undefined (and therefore falsy), but anyway the PR looks good to me. Would you mind to reopen to develop?

**Comment by netgusto** [comment]
> Would you mind to reopen to develop?

Not sure what you mean ? The PR is open ?

**Comment by netgusto** [comment]
> not sure how the current validation is affecting you, since a non-existing property would be undefined (and therefore falsy)

actually, undefined being falsy is the problem when the default value of the option happens to be true (like with `rejectUnauthorized` for instance) :

```diff
-    if (config.rejectUnauthorized) options.rejectUnauthorized = config.rejectUnauthorized;
+    if ('rejectUnauthorized' in config) options.rejectUnauthorized = config.rejectUnauthorized;
```

If `rejectUnauthorized` is explicitely set to `false` in config, in the current version of the code, `options.rejectUnauthorized = config.rejectUnauthorized` would not be executed, and therefore `rejectUnauthorized` would still be set to it's default value (`true`).

**Comment by jonathansamines** [comment]
HI @netgusto I see now what the problem actually is. The only thing is that, PR are only accepted to be merged to developer, and this PR is pointing to the project master branch. That is why I was requesting to create a new one (or edit this if possible) to point to develop.

**Comment by jonathansamines** [comment]
His should be already solved in 1.0.0

**Pull request closed without merging**
